/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '/amortizations/': RouteRecordInfo<'/amortizations/', '/amortizations', Record<never, never>, Record<never, never>>,
    '/amortizations/[id]': RouteRecordInfo<'/amortizations/[id]', '/amortizations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'simulations': RouteRecordInfo<'simulations', '/simulations', Record<never, never>, Record<never, never>>,
    '/simulations/[id]': RouteRecordInfo<'/simulations/[id]', '/simulations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
  }
}
